package io.github.harryjhin.slf4j.ktx.compiler

import org.jetbrains.kotlin.GeneratedDeclarationKey

/**
 * Identity used to tag declarations generated by the slf4j-ktx compiler plugin.
 *
 * In K2 IR this object appears as `IrDeclarationOrigin.GeneratedByPlugin(Slf4jKtxPluginKey)` on
 * every property/function our frontend synthesizes, letting the backend distinguish plugin-
 * originated declarations from user code. Mirrors kotlinx-serialization's `SerializationPluginKey`.
 */
object Slf4jKtxPluginKey : GeneratedDeclarationKey()
