name: Publish

on:
  workflow_dispatch:
  push:
    tags: ["v*"]

jobs:
  publish:
    environment: maven
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: temuion
          cache: gradle

      - uses: gradle/actions/wrapper-validation@v4

      - name: Run tests
        run: ./gradlew check

      - name: Publish to Maven Central
        run: ./gradlew publish
        env:
          ORG_GRADLE_PROJECT_deploy-url: https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/
          ORG_GRADLE_PROJECT_deploy-username: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_deploy-password: ${{ secrets.SONATYPE_PASSWORD }}
          ORG_GRADLE_PROJECT_signKeyId: ${{ secrets.SIGN_KEY_ID }}
          ORG_GRADLE_PROJECT_signKeyPrivate: ${{ secrets.SIGN_KEY_PRIVATE }}
          ORG_GRADLE_PROJECT_signKeyPassphrase: ${{ secrets.SIGN_KEY_PASSPHRASE }}

      - name: Create GitHub Release
        run: gh release create ${{ github.ref_name }} --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
